### PR TITLE
Add 2 artifacts in portal meta.json

### PR DESCRIPTION
**Pull request by ndkhanh-axonivy**

### CODE REVIEW

**Comment by ntqdinh-axonivy** [comment]
Hi @ndkhanh-axonivy 
Please create the similar PR in https://github.com/axonivy-market/market.
This code change only affect local env not prod.
Thanks.

**Comment by ndkhanh-axonivy** [comment]
Portal team will deploy portal-product/product.json. So we don't need to have this PR anymore.

**Comment by alexsuter** [comment]
If you close a PR, please also delete the branch. I'll do this now.

**Comment by ndkhanh-axonivy** [comment]
Thanks so much for the reminder, Alex. I'll be more mindful of this in the future.

**Pull request closed without merging**
